/*
PROYECTO FINAL OBJETOS Y ABSTRACCION DE DATOS
Jorge Vinueza :v
-----------------------------------
 */
package miprimeraaplicacioncs;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class FrmPedido extends javax.swing.JFrame {
    private PedidoBeans pedidoBeans;

    public FrmPedido() {
        initComponents();
        try {
            pedidoBeans = new PedidoBeans();//1  ta
            rellenarComboBoxCant();
        } catch (Exception e) {
            e.printStackTrace();
            //T= ta
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cant2 = new javax.swing.JComboBox<>();
        cant3 = new javax.swing.JComboBox<>();
        cant5 = new javax.swing.JComboBox<>();
        cant1 = new javax.swing.JComboBox<>();
        cant4 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        plato1 = new javax.swing.JRadioButton();
        plato2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        plato4 = new javax.swing.JRadioButton();
        plato5 = new javax.swing.JRadioButton();
        p2 = new javax.swing.JTextField();
        p3 = new javax.swing.JTextField();
        p4 = new javax.swing.JTextField();
        p5 = new javax.swing.JTextField();
        p1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPedido = new javax.swing.JTable();
        btnregresar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cant2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cant2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));
        cant2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cant2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cant2ActionPerformed(evt);
            }
        });
        jPanel1.add(cant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 50, 20));

        cant3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cant3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));
        cant3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cant3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cant3ActionPerformed(evt);
            }
        });
        jPanel1.add(cant3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 50, 20));

        cant5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cant5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));
        cant5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cant5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cant5ActionPerformed(evt);
            }
        });
        jPanel1.add(cant5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 50, 20));

        cant1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cant1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));
        cant1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cant1ActionPerformed(evt);
            }
        });
        jPanel1.add(cant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 50, 20));

        cant4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cant4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));
        cant4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cant4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cant4ActionPerformed(evt);
            }
        });
        jPanel1.add(cant4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 50, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miprimeraaplicacioncs/carne.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 200, 170));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miprimeraaplicacioncs/ceviche.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 239, 151));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miprimeraaplicacioncs/encebollado.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 204, 170));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miprimeraaplicacioncs/bolon.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 42, 206, 170));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miprimeraaplicacioncs/postre.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 206, 139));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MENU");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 75, 43));

        jButton1.setText("Guardar Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        plato1.setText("Arroz con carne");
        jPanel1.add(plato1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 110, 20));

        plato2.setText("Ceviche");
        jPanel1.add(plato2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 110, -1));

        jRadioButton1.setText("Encebollado");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 110, 20));

        plato4.setText("Bolon");
        jPanel1.add(plato4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 110, 20));

        plato5.setText("Postre");
        jPanel1.add(plato5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 110, 20));

        p2.setEditable(false);
        p2.setText("2");
        jPanel1.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 20, 20));

        p3.setEditable(false);
        p3.setText("3");
        jPanel1.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 20, 20));

        p4.setEditable(false);
        p4.setText("4");
        jPanel1.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 20, 20));

        p5.setEditable(false);
        p5.setText("5");
        jPanel1.add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 20, 20));

        p1.setEditable(false);
        p1.setText("1");
        jPanel1.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 20, 20));

        jtPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "N°", "Plato", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane1.setViewportView(jtPedido);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 600, 90));

        btnregresar.setText("REGRESAR");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        jMenu1.setText("Volver");
        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cant2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cant2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cant2ActionPerformed

    private void cant4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cant4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cant4ActionPerformed

    private void cant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cant1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cant1ActionPerformed

    private void cant5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cant5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cant5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.ingreso();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cant3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cant3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cant3ActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        // TODO add your handling code here:
        FrmIngreso in =new FrmIngreso();//1  ta
        this.setVisible(false);
        in.setVisible(true);                 
        //T= ta
    }//GEN-LAST:event_btnregresarActionPerformed

    /**
     * @param args the command line arguments
     */
    private void rellenarComboBoxCant() {
        // Agregar valores del 0 al 10 al combobox "cant"
        for (int i = 0; i <= 10; i++) {//1  n(ta + tc + to)
            cant1.addItem(Integer.toString(i));
            cant2.addItem(Integer.toString(i));
            cant3.addItem(Integer.toString(i));
            cant4.addItem(Integer.toString(i));
            cant5.addItem(Integer.toString(i));
        }
        //Tiempo= n(ta + tc + to)
    }

    private void ingreso() {
        int idPlato = -1;//1  ta
        int cantidad = 0;//2  ta
        double precio = 0.0;//3  ta

        if (plato1.isSelected()) {//4  n(tc)
            idPlato = 1;//5  ta
        } else if (plato2.isSelected()) {//6  n(tc)
            idPlato = 2;//7  ta
        } else if (jRadioButton1.isSelected()) {//8  n(tc)
            idPlato = 3;//9  ta
        } else if (plato4.isSelected()) {//10  n(tc)
            idPlato = 4;//11  ta
        } else if (plato5.isSelected()) {//12  n(tc)
            idPlato = 5;//13  ta
        }

        if (idPlato != -1) {//14  n(tc) + tc

            JComboBox<String> comboBoxCantidad = null;//15  ta
            switch (idPlato) {
                case 1:
                    comboBoxCantidad = cant1; //16  ta
                    precio = 3.0; // Precio del plato 1  //17  ta
                    break;
                case 2:
                    comboBoxCantidad = cant2;  //18  ta
                    precio = 1.0; // Precio del plato 2  //19  ta
                    break;
                case 3:
                    comboBoxCantidad = cant3;//20  ta
                    precio = 2.0; // Precio del plato 3 //21  ta
                    break;
                case 4:
                    comboBoxCantidad = cant4; //22  ta
                    precio = 1.50; // Precio del plato 4 //23  ta
                    break;
                case 5:
                    comboBoxCantidad = cant5;  //24  ta
                    precio = 3.0; // Precio del plato 5  //25  ta
                    break;
            }

            if (comboBoxCantidad != null) { //25  n(tc)+tc
                cantidad = Integer.parseInt(comboBoxCantidad.getSelectedItem().toString());
            }
        }

        if (idPlato != -1 && cantidad != 0) {//26  n(tc)+tc+ tc
            try {
                double total = cantidad * precio;//27  ta + to
                pedidoBeans.setId_plato(idPlato);
                pedidoBeans.setCantidad(cantidad);
                pedidoBeans.setPrecio(precio);
                pedidoBeans.setTotal(total);

                pedidoBeans.Insertar_Pedido();

                actualizarTablaPedidos();
            } catch (SQLException e) {
                e.printStackTrace();
            }
            /*Tiempo del metodo
            Mejor tiempo esperado
            T= ta+ta+ta+tc+ta+tc+ta+tc+ta+tc+ta+tc+ta+tc+tc+ta+ta+ta+ta+ta+ta+ta+ta+ta+ta+ta+tc+tc+tc+tc+tc+ta+to
            T= 20ta + 12tc + to
            
            Peor tiempo esperado
            T= ta+ta+ta+ntc+ta+ntc+ta+ntc+ta+ntc+ta+ntc+ta+ntc+tc+ta+ta+ta+ta+ta+ta+ta+ta+ta+ta+ta+ntc+tc+ntc+tc+tc+ta+to
            T= 20ta + 4tc + to + 8ntc
            
            Tiempo promedio
            T= [Tm + Tp]/2
            T= [20ta + 12tc + to + 20ta + 4tc + to + 8ntc]/2
            T= [40ta + 16tc + 2to + 8ntc]/2
            T= [2(20ta + 8tc + to) + 8ntc]/2
            */
        }
    }

    private void actualizarTablaPedidos() throws SQLException {
        ResultSet rs = pedidoBeans.consultaTabla("SELECT * FROM pedido");//1  ta

        DefaultTableModel modelo = new DefaultTableModel();//2  ta
        modelo.addColumn("N°");
        modelo.addColumn("Plato");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        modelo.addColumn("Total");

        while (rs.next()) {//3   n(tc)
            Object[] fila = new Object[5];//4  n(ta)
            fila[0] = rs.getInt(1);//5  n(ta)
            fila[1] = rs.getString(2);//6  n(ta)
            fila[2] = rs.getString(3);//7  n(ta)
            fila[3] = rs.getDouble(4); //8  n(ta)
            fila[4] = rs.getDouble(5); //9  n(ta)
            modelo.addRow(fila);
        }
        //Tiempo del metodo
        //T= ta + ta + ntc + nta + nta+ nta + nta + nta + nta
        //T= 2ta + 6nta + ntc
        //T= 2ta + n(6ta + tc)

        jtPedido.setModel(modelo);
    }





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregresar;
    private javax.swing.JComboBox<String> cant1;
    private javax.swing.JComboBox<String> cant2;
    private javax.swing.JComboBox<String> cant3;
    private javax.swing.JComboBox<String> cant4;
    private javax.swing.JComboBox<String> cant5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtPedido;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField p3;
    private javax.swing.JTextField p4;
    private javax.swing.JTextField p5;
    private javax.swing.JRadioButton plato1;
    private javax.swing.JRadioButton plato2;
    private javax.swing.JRadioButton plato4;
    private javax.swing.JRadioButton plato5;
    // End of variables declaration//GEN-END:variables

    private void mostrar(JTable jtPedido, String selectfrom_clientes) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   
}
